version: 2.1
orbs:
  codecov: codecov/codecov@1.0.3
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2-stretch-node-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: set up env
          command: |
            git config --global user.email "circle@ci.example.com"
            git config --global user.name "Circle Ci"
            python3 -m venv venv
            . venv/bin/activate
            pip install -Ue .[dev]

      - run:
          name: check style
          command: |
            . venv/bin/activate
            flake8 src tests

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m pytest --cov=lektorium --cov-report=xml


      - codecov/upload:
          file: coverage.xml
          token: 154a6f93-3f50-40bb-b3e9-d3c18fa3c626
