version: 2.1
orbs:
  codecov: codecov/codecov@1.0.3
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2-stretch-node-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            - v1-dependencies-

      - run:
          name: set up env
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .[dev]

      - run:
          name: check style
          command: |
            . venv/bin/activate
            flake8 ./

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m pytest --cov-report xml


      - codecov/upload:
          file: coverage.xml
          token: 154a6f93-3f50-40bb-b3e9-d3c18fa3c626

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
