site:
  name: Example site
  custodian: 
    name: Max Jekov
    email: mj@acme.com
  production: 
    url: www.example.com
  staging:
    url: test.example.com
  functions:
    func1: f1
  edit:
    session_id: widgets-1
    build_url: build.example.com
    creation_time: 2019-07-19 10:33 UTC+1
  parked:
    session_id: widgets-1
    creation_time: 2019-07-19 10:33 UTC+1
  repo:
    name: Example.com Repo
    url: https://example.com.git
  admins: 
    - user: Zillent
      email: serg@zillent.ru
    - user: Max Jekov
      email: mj@acme.com
  editors: 
    - user: Zillent
      email: serg@zillent.ru
    - user: Max Jekov
      email: mj@acme.com
  