name: python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: pip caching
      uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: dependencies
      run: |
        sudo apt-get update
        sudo apt-get -y install git
        python -m pip install --upgrade pip
        pip install -e .[dev]
        pip install spherical-dev[dev]
    - name: isort and flake8
      run: |
        inv isort -c
        inv flake
    - name: tests
      run: |
        inv test
